name: 'AreaConnect'
version: '1.0.0'
api-version: '1.18'
author: 'ThePotatoCamera'
website: 'https://discord.a223.es'
main: 'es.a223.areaconnect.AreaConnect'
commands:
  areaconnect:
    description: 'Gestionar el plugin de AreaConnect'
    aliases:
      - area-connect
      - a223
    usage: /<command> [reload | link | adddinero]
    permission: areaconnect.reload
permissions:
  areaconnect.*:
    description: 'Acceso adminstrativo del plugin'
    default: op
    children:
      - areaconnect.reload
      - areaconnect.link
      - areaconnect.adddinero
  areaconnect.reload:
    description: 'Permite recargar el plugin'
    default: op
  areaconnect.link:
    description: 'Permite enlazar una cuenta de Minecraft a una cuenta de Discord'
    default: true
  areaconnect.unlink:
    description: 'Permite desenlazar una cuenta de Minecraft de una cuenta de Discord'
    default: true
  areaconnect.adddinero:
    description: 'Permite añadir dinero a un usuario.'
    default: op